package com.ericsson.csp.tsc.admin.dao.entity;

// Generated 2015-10-13 17:16:11 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.SimplePropertyPreFilter;
import com.ericsson.csp.tsc.admin.util.PaginationRow;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", schema = "public")
public class SysRole implements java.io.Serializable, PaginationRow {

    private static final long serialVersionUID = 2433049450911879851L;

    private int               id;

    private String            name;

    private boolean           isBuiltin;

    private Date              updateTime;

    private Date              createTime;

    public SysRole() {
    }

    public SysRole(int id, String name, boolean isBuiltin, Date updateTime, Date createTime) {
        this.id = id;
        this.name = name;
        this.isBuiltin = isBuiltin;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public SysRole(String name, boolean isBuiltin, Date updateTime, Date createTime) {
        this.name = name;
        this.isBuiltin = isBuiltin;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    @Id
    @SequenceGenerator(name = "geely_sequences", sequenceName = "geely_sequences", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "geely_sequences")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, unique = true, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "is_builtin", nullable = false)
    public boolean isIsBuiltin() {
        return this.isBuiltin;
    }

    public void setIsBuiltin(boolean isBuiltin) {
        this.isBuiltin = isBuiltin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", nullable = false, length = 22)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 22)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JSONField(serialize = false)
    @Override
    @Transient
    public SimplePropertyPreFilter fetchSimplePropertyPreFilter() {
        SimplePropertyPreFilter filter = new SimplePropertyPreFilter(SysUser.class, "id", "name", "isBuiltin",
                "updateTime", "createTime");
        return filter;
    }

}
