package com.ericsson.csp.tsc.admin.dao.entity;

// Generated 2015-10-10 13:46:24 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.SimplePropertyPreFilter;
import com.ericsson.csp.tsc.admin.util.PaginationRow;

import org.hibernate.validator.constraints.NotBlank;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user")
public class SysUser implements java.io.Serializable, PaginationRow {

    private static final long serialVersionUID = 5283986634527499220L;

    @JSONField(name = "id")
    private Integer           id;

    @JSONField(name = "loginName")
    @NotBlank(message = "loginName is required.")
    private String            loginName;

    @JSONField(name = "password")
    @NotBlank(message = "password is required.")
    private String            password;

    @JSONField(name = "name")
    @NotBlank(message = "name is required.")
    private String            name;

    @JSONField(name = "phone")
    @NotBlank(message = "phone is required.")
    private String            phone;

    @JSONField(name = "email")
    private String            email;

    @JSONField(name = "sex")
    private Integer           sex;

    private boolean           isBuiltin;

    private Date              loginTime;

    private Date              passwordLastModifyTime;

    @JSONField(name = "updateTime")
    private Date              updateTime;

    @JSONField(name = "createTime")
    private Date              createTime;

    public SysUser() {
    }

    public SysUser(Integer id, String loginName, String password, boolean isBuiltin, Date updateTime, Date createTime) {
        this.id = id;
        this.loginName = loginName;
        this.password = password;
        this.isBuiltin = isBuiltin;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public SysUser(Integer id, String loginName, String password, String name, String phone, String email,
            boolean isBuiltin, Date loginTime, Date passwordLastModifyTime, Date updateTime, Date createTime) {
        this.id = id;
        this.loginName = loginName;
        this.password = password;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.isBuiltin = isBuiltin;
        this.loginTime = loginTime;
        this.passwordLastModifyTime = passwordLastModifyTime;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public SysUser(String loginName, String password, String name, String phone, String email, boolean isBuiltin,
            Date loginTime, Date passwordLastModifyTime, Date updateTime, Date createTime) {
        this.loginName = loginName;
        this.password = password;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.isBuiltin = isBuiltin;
        this.loginTime = loginTime;
        this.passwordLastModifyTime = passwordLastModifyTime;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    @Id
    @SequenceGenerator(name = "geely_sequences", sequenceName = "geely_sequences", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "geely_sequences")
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "login_name", nullable = false, unique = true, length = 100)
    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Column(name = "password", nullable = false, length = 200)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "name", length = 32)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "phone", length = 32)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "email", length = 64)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "sex")
    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    @Column(name = "is_builtin", nullable = false)
    public boolean isIsBuiltin() {
        return this.isBuiltin;
    }

    public void setIsBuiltin(boolean isBuiltin) {
        this.isBuiltin = isBuiltin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "login_time", length = 22)
    public Date getLoginTime() {
        return this.loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "password_last_modify_time", length = 22)
    public Date getPasswordLastModifyTime() {
        return this.passwordLastModifyTime;
    }

    public void setPasswordLastModifyTime(Date passwordLastModifyTime) {
        this.passwordLastModifyTime = passwordLastModifyTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", nullable = false, length = 22)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 22)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    @Transient
    public SimplePropertyPreFilter fetchSimplePropertyPreFilter() {
        SimplePropertyPreFilter filter = new SimplePropertyPreFilter(SysUser.class, "id", "loginName", "name", "phone",
                "sex", "email", "updateTime", "createTime");
        return filter;
    }

}
